CREATE EXTENSION IF NOT EXISTS postgis;

DROP TABLE IF EXISTS public.poc_buildings;

CREATE TABLE public.poc_buildings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    building_type text NOT NULL,
    base_height_m double precision NOT NULL DEFAULT 0.0,
    height_m double precision NOT NULL CHECK (height_m > 0),
    color text NOT NULL DEFAULT '#b8b2a6',
    geom geometry(MultiPolygon, 4326) NOT NULL,
    CONSTRAINT poc_buildings_geom_valid CHECK (ST_IsValid(geom)),
    CONSTRAINT poc_buildings_geom_non_empty CHECK (NOT ST_IsEmpty(geom)),
    CONSTRAINT poc_buildings_base_height_limit CHECK (base_height_m >= 0 AND base_height_m <= 1000),
    CONSTRAINT poc_buildings_height_limit CHECK (height_m <= 500)
);

INSERT INTO public.poc_buildings (name, building_type, base_height_m, height_m, color, geom)
VALUES
    (
        'Sansome Office',
        'office',
        4.0,
        96.0,
        '#8aa1b1',
        ST_Multi(ST_GeomFromText(
            'POLYGON((
                -122.40120 37.79252,
                -122.40082 37.79252,
                -122.40082 37.79282,
                -122.40120 37.79282,
                -122.40120 37.79252
            ))',
            4326
        ))
    ),
    (
        'Battery Mixed Use',
        'mixed_use',
        0.0,
        64.0,
        '#c29f75',
        ST_Multi(ST_GeomFromText(
            'POLYGON((
                -122.40072 37.79255,
                -122.40035 37.79255,
                -122.40035 37.79284,
                -122.40072 37.79284,
                -122.40072 37.79255
            ))',
            4326
        ))
    ),
    (
        'Market Annex',
        'retail',
        2.0,
        28.0,
        '#b7a99a',
        ST_Multi(ST_GeomFromText(
            'POLYGON((
                -122.40025 37.79250,
                -122.39986 37.79250,
                -122.39986 37.79276,
                -122.40025 37.79276,
                -122.40025 37.79250
            ))',
            4326
        ))
    ),
    (
        'Clay Tower',
        'office',
        6.0,
        88.0,
        '#889b8f',
        ST_Multi(ST_GeomFromText(
            'POLYGON((
                -122.40112 37.79302,
                -122.40078 37.79302,
                -122.40078 37.79334,
                -122.40112 37.79334,
                -122.40112 37.79302
            ))',
            4326
        ))
    ),
    (
        'Pine Residential',
        'residential',
        3.0,
        42.0,
        '#a98f8f',
        ST_Multi(ST_GeomFromText(
            'POLYGON((
                -122.40062 37.79306,
                -122.40022 37.79306,
                -122.40022 37.79336,
                -122.40062 37.79336,
                -122.40062 37.79306
            ))',
            4326
        ))
    ),
    (
        'Corner Pavilion',
        'civic',
        0.0,
        18.0,
        '#9da7bf',
        ST_Multi(ST_GeomFromText(
            'POLYGON((
                -122.40010 37.79300,
                -122.39982 37.79300,
                -122.39982 37.79324,
                -122.40010 37.79324,
                -122.40010 37.79300
            ))',
            4326
        ))
    );

CREATE INDEX poc_buildings_geom_gix ON public.poc_buildings USING gist (geom);

ANALYZE public.poc_buildings;
